ERROR - 2022-10-31 18:08:20,979 - GmailReader - error | (psycopg2.OperationalError) connection to server at "database-2.ccknekyc13f2.ap-south-1.rds.amazonaws.com" (10.120.21.231), port 5432 failed: Connection timed out (0x0000274C/10060)
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8) <class 'sqlalchemy.exc.OperationalError'> database.py, Line 28
ERROR - 2022-10-31 18:35:19,890 - GmailReader - error | type object 'GenerateRules' has no attribute 'rules_attributes' <class 'AttributeError'> crud.py, Line 14
ERROR - 2022-10-31 18:35:41,270 - GmailReader - error | type object 'GenerateRules' has no attribute 'rules_attributes' <class 'AttributeError'> crud.py, Line 14
ERROR - 2022-10-31 18:35:41,270 - GmailReader - error | type object 'GenerateRules' has no attribute 'rules_attributes' <class 'AttributeError'> crud.py, Line 14
ERROR - 2022-10-31 18:35:41,628 - GmailReader - error | type object 'GenerateRules' has no attribute 'rules_attributes' <class 'AttributeError'> crud.py, Line 14
ERROR - 2022-10-31 18:35:41,628 - GmailReader - error | type object 'GenerateRules' has no attribute 'rules_attributes' <class 'AttributeError'> crud.py, Line 14
ERROR - 2022-10-31 18:35:41,628 - GmailReader - error | type object 'GenerateRules' has no attribute 'rules_attributes' <class 'AttributeError'> crud.py, Line 14
ERROR - 2022-10-31 18:35:42,011 - GmailReader - error | type object 'GenerateRules' has no attribute 'rules_attributes' <class 'AttributeError'> crud.py, Line 14
ERROR - 2022-10-31 18:35:42,011 - GmailReader - error | type object 'GenerateRules' has no attribute 'rules_attributes' <class 'AttributeError'> crud.py, Line 14
ERROR - 2022-10-31 18:35:42,011 - GmailReader - error | type object 'GenerateRules' has no attribute 'rules_attributes' <class 'AttributeError'> crud.py, Line 14
ERROR - 2022-10-31 18:35:42,011 - GmailReader - error | type object 'GenerateRules' has no attribute 'rules_attributes' <class 'AttributeError'> crud.py, Line 14
ERROR - 2022-10-31 18:35:50,175 - GmailReader - error | fees_type <class 'AttributeError'> crud.py, Line 39
ERROR - 2022-10-31 18:35:50,175 - GmailReader - error | fees_type <class 'AttributeError'> crud.py, Line 39
ERROR - 2022-10-31 18:35:50,175 - GmailReader - error | fees_type <class 'AttributeError'> crud.py, Line 39
ERROR - 2022-10-31 18:35:50,175 - GmailReader - error | fees_type <class 'AttributeError'> crud.py, Line 39
ERROR - 2022-10-31 18:35:50,175 - GmailReader - error | fees_type <class 'AttributeError'> crud.py, Line 39
ERROR - 2022-10-31 18:35:50,553 - GmailReader - error | fees_type <class 'AttributeError'> crud.py, Line 39
ERROR - 2022-10-31 18:35:50,553 - GmailReader - error | fees_type <class 'AttributeError'> crud.py, Line 39
ERROR - 2022-10-31 18:35:50,553 - GmailReader - error | fees_type <class 'AttributeError'> crud.py, Line 39
ERROR - 2022-10-31 18:35:50,553 - GmailReader - error | fees_type <class 'AttributeError'> crud.py, Line 39
ERROR - 2022-10-31 18:35:50,553 - GmailReader - error | fees_type <class 'AttributeError'> crud.py, Line 39
ERROR - 2022-10-31 18:35:50,553 - GmailReader - error | fees_type <class 'AttributeError'> crud.py, Line 39
